using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEditor.TestTools.TestRunner.Api;
using UnityEngine;

namespace Tabletop.EditorTools
{
    /// <summary>
    /// Runs the EditMode/PlayMode suites and writes a plain-text summary to Logs/TestResults-*.txt
    /// (survives the domain reloads that PlayMode tests cause). Also makes the Windows development build.
    /// </summary>
    [InitializeOnLoad]
    public static class TestAndBuildTools
    {
        private const string PendingKey = "Tabletop.PendingTestRun";
        public const string BuildPath = "Builds/Windows/TabletopReels.exe";

        static TestAndBuildTools()
        {
            var api = ScriptableObject.CreateInstance<TestRunnerApi>();
            api.RegisterCallbacks(new ResultWriter());
        }

        /// <summary>
        /// EditMode tests build temporary objects in whatever scene is open, which marks it modified; the next run
        /// then stops on Unity's "save changes?" dialog and waits forever when nobody is at the keyboard.
        /// World.unity and MatchPrototype.unity are generated by code (Tabletop/Setup), so reload them from disk.
        /// An unsaved Untitled scene (the test runner's own) is replaced by World.unity. Any other modified scene is
        /// left alone (it may hold someone's real work).
        /// </summary>
        private static void DiscardTestLeftoversInGeneratedScene()
        {
            var active = UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene();
            if (!active.isDirty) return;
            if (active.path == WorldSceneSetup.WorldScenePath || active.path == ProjectSetup.ScenePath)
            {
                Debug.Log("[Tabletop] Reloading " + active.path + " before tests (it is generated by code; unsaved changes are test leftovers).");
                UnityEditor.SceneManagement.EditorSceneManager.OpenScene(active.path);
            }
            else if (string.IsNullOrEmpty(active.path))
            {
                // The test runner's own "Untitled" scene from a previous run.
                Debug.Log("[Tabletop] Opening " + WorldSceneSetup.WorldScenePath + " before tests (replacing an unsaved Untitled test scene).");
                UnityEditor.SceneManagement.EditorSceneManager.OpenScene(WorldSceneSetup.WorldScenePath);
            }
        }

        [MenuItem("Tabletop/Tests/Run EditMode")]
        public static void RunEditMode() => Run(TestMode.EditMode);

        [MenuItem("Tabletop/Tests/Run PlayMode")]
        public static void RunPlayMode() => Run(TestMode.PlayMode);

        public static void Run(TestMode mode, string testNameFilter = null)
        {
            DiscardTestLeftoversInGeneratedScene();
            SessionState.SetString(PendingKey, mode.ToString());
            var path = ResultPath(mode);
            if (File.Exists(path)) File.Delete(path);
            File.WriteAllText(path, "RUNNING " + mode + " " + System.DateTime.Now.ToString("s") + "\n");
            var api = ScriptableObject.CreateInstance<TestRunnerApi>();
            // Only this project's suites (the Input System package is "testable" for its test fixture).
            var filter = new Filter { testMode = mode, assemblyNames = new[] { mode == TestMode.PlayMode ? "Tabletop.Tests.PlayMode" : "Tabletop.Tests.EditMode" } };
            if (!string.IsNullOrEmpty(testNameFilter)) filter.testNames = new[] { testNameFilter };
            api.Execute(new ExecutionSettings(filter));
        }

        public static string ResultPath(TestMode mode) => Path.Combine("Logs", "TestResults-" + mode + ".txt");

        private sealed class ResultWriter : ICallbacks
        {
            public void RunStarted(ITestAdaptor testsToRun) { }
            public void TestStarted(ITestAdaptor test) { }
            public void TestFinished(ITestResultAdaptor result) { }

            public void RunFinished(ITestResultAdaptor result)
            {
                string modeName = SessionState.GetString(PendingKey, "Unknown");
                var sb = new StringBuilder();
                sb.AppendLine("FINISHED " + modeName + " " + System.DateTime.Now.ToString("s"));
                sb.AppendLine("Result: " + result.TestStatus + "  passed=" + result.PassCount + " failed=" + result.FailCount
                    + " skipped=" + result.SkipCount + " inconclusive=" + result.InconclusiveCount + " duration=" + result.Duration.ToString("0.0") + "s");
                Collect(result, sb);
                Directory.CreateDirectory("Logs");
                var mode = modeName == "PlayMode" ? TestMode.PlayMode : TestMode.EditMode;
                File.WriteAllText(ResultPath(mode), sb.ToString());
                Debug.Log("[Tabletop] Tests " + modeName + ": " + result.TestStatus + " passed=" + result.PassCount + " failed=" + result.FailCount);
            }

            private static void Collect(ITestResultAdaptor r, StringBuilder sb)
            {
                if (!r.HasChildren)
                {
                    sb.Append(r.TestStatus == TestStatus.Passed ? "  PASS " : "  " + r.TestStatus.ToString().ToUpperInvariant() + " ")
                      .Append(r.Test.FullName).Append(" (").Append(r.Duration.ToString("0.00")).AppendLine("s)");
                    if (r.TestStatus == TestStatus.Failed)
                    {
                        sb.AppendLine("    " + (r.Message ?? "").Replace("\n", "\n    "));
                        sb.AppendLine("    " + (r.StackTrace ?? "").Replace("\n", "\n    "));
                    }
                    return;
                }
                foreach (var c in r.Children) Collect(c, sb);
            }
        }

        public const string WindowsZipPath = "Builds/TabletopReels-Windows.zip";

        [MenuItem("Tabletop/Build/Windows x64 Development Build")]
        public static void BuildWindows()
        {
            Directory.CreateDirectory(Path.GetDirectoryName(BuildPath));
            var options = new BuildPlayerOptions
            {
                scenes = new[] { WorldSceneSetup.WorldScenePath, ProjectSetup.ScenePath },
                locationPathName = BuildPath,
                target = BuildTarget.StandaloneWindows64,
                options = BuildOptions.Development,
            };
            var report = BuildPipeline.BuildPlayer(options);
            var summary = report.summary;
            string line = "[Tabletop] Build " + summary.result + ": " + summary.outputPath + " size=" + summary.totalSize + " errors=" + summary.totalErrors
                + " warnings=" + summary.totalWarnings + " time=" + summary.totalTime + " " + ModelsIn(report);
            if (summary.result == BuildResult.Succeeded)
                line += " zip=" + WindowsZipPath + " (" + ZipForTesters(Path.GetDirectoryName(BuildPath), WindowsZipPath) + " MB)";
            File.WriteAllText(Path.Combine("Logs", "BuildResult.txt"), line + "\n");
            if (summary.result == BuildResult.Succeeded) Debug.Log(line); else Debug.LogError(line);
        }

        /// <summary>Windows, then the iOS Xcode project (D-030). Results in Logs/BuildResult*.txt.</summary>
        [MenuItem("Tabletop/Build/All (Windows + iOS)")]
        public static void BuildAll()
        {
            BuildWindows();
            BuildIOS();
        }

        /// <summary>How many imported model files went into a build (shelved models must be 0, D-030).</summary>
        public static string ModelsIn(BuildReport report)
        {
            var people = new System.Collections.Generic.HashSet<string>();
            var buildings = new System.Collections.Generic.HashSet<string>();
            foreach (var packed in report.packedAssets)
                foreach (var info in packed.contents)
                {
                    var src = info.sourceAssetPath ?? "";
                    if (!src.EndsWith(".fbx", System.StringComparison.OrdinalIgnoreCase)) continue;
                    if (src.StartsWith("Assets/Game/Characters/")) people.Add(src);
                    else if (src.StartsWith("Assets/Game/Buildings/")) buildings.Add(src);
                }
            return "peopleModels=" + people.Count + " buildingModels=" + buildings.Count;
        }

        /// <summary>Zips a build folder for sharing, leaving out Unity's debug-symbol folders ("DoNotShip"). Returns MB.</summary>
        private static long ZipForTesters(string folder, string zipPath)
        {
            if (File.Exists(zipPath)) File.Delete(zipPath);
            string root = Path.GetFullPath(folder);
            string top = Path.GetFileName(root.TrimEnd('/', '\\'));
            using (var zip = System.IO.Compression.ZipFile.Open(zipPath, System.IO.Compression.ZipArchiveMode.Create))
            {
                foreach (var file in Directory.GetFiles(root, "*", SearchOption.AllDirectories))
                {
                    string rel = file.Substring(root.Length).TrimStart('/', '\\').Replace('\\', '/');
                    if (rel.Contains("DoNotShip")) continue;
                    System.IO.Compression.ZipFileExtensions.CreateEntryFromFile(zip, file, top + "/" + rel, System.IO.Compression.CompressionLevel.Optimal);
                }
            }
            return new FileInfo(zipPath).Length / (1024 * 1024);
        }

        public const string IosProjectPath = "Builds/iOS/TabletopReels";
        public const string IosZipPath = "Builds/TabletopReels-iOS-Xcode.zip";
        public const string IosBundleId = "com.scootsy.tabletopreels";

        /// <summary>
        /// iPhone / iPad development build (D-029): Unity on Windows writes an Xcode project, which is finished,
        /// signed and installed on a Mac with Xcode. Needs the iOS Build Support module. The editor is switched
        /// back to Windows afterwards so tests and the Windows build are unaffected.
        /// </summary>
        [MenuItem("Tabletop/Build/iOS Xcode Project (iPhone + iPad)")]
        public static void BuildIOS()
        {
            PlayerSettings.SetApplicationIdentifier(UnityEditor.Build.NamedBuildTarget.iOS, IosBundleId);
            PlayerSettings.iOS.targetDevice = iOSTargetDevice.iPhoneAndiPad;
            PlayerSettings.iOS.targetOSVersionString = "15.0";
            PlayerSettings.iOS.requiresFullScreen = true;
            PlayerSettings.iOS.appleEnableAutomaticSigning = true; // pick your team in Xcode > Signing & Capabilities
            // The table is a landscape game.
            PlayerSettings.defaultInterfaceOrientation = UIOrientation.AutoRotation;
            PlayerSettings.allowedAutorotateToLandscapeLeft = true;
            PlayerSettings.allowedAutorotateToLandscapeRight = true;
            PlayerSettings.allowedAutorotateToPortrait = false;
            PlayerSettings.allowedAutorotateToPortraitUpsideDown = false;

            if (Directory.Exists(IosProjectPath)) Directory.Delete(IosProjectPath, true);
            Directory.CreateDirectory(IosProjectPath);
            var options = new BuildPlayerOptions
            {
                scenes = new[] { WorldSceneSetup.WorldScenePath, ProjectSetup.ScenePath },
                locationPathName = IosProjectPath,
                target = BuildTarget.iOS,
                options = BuildOptions.Development,
            };
            BuildReport report;
            try
            {
                report = BuildPipeline.BuildPlayer(options);
            }
            finally
            {
                EditorUserBuildSettings.SwitchActiveBuildTarget(BuildTargetGroup.Standalone, BuildTarget.StandaloneWindows64);
            }
            var summary = report.summary;
            string line = "[Tabletop] iOS build " + summary.result + ": " + summary.outputPath + " errors=" + summary.totalErrors
                + " warnings=" + summary.totalWarnings + " time=" + summary.totalTime + " " + ModelsIn(report);
            if (summary.result == BuildResult.Succeeded)
                line += " zip=" + IosZipPath + " (" + ZipForTesters(IosProjectPath, IosZipPath) + " MB)";
            File.WriteAllText(Path.Combine("Logs", "BuildResult-iOS.txt"), line + "\n");
            if (summary.result == BuildResult.Succeeded) Debug.Log(line); else Debug.LogError(line);
        }
    }
}
