using System;
using System.Collections.Generic;
using UnityEngine;

namespace Tabletop.Presentation
{
    /// <summary>Placeholder icon sprites (generated by Tools/Art/make_icons.py). Referenced explicitly by MatchApp.</summary>
    [CreateAssetMenu(menuName = "Tabletop/Icon Set", fileName = "IconSet")]
    public sealed class IconSet : ScriptableObject
    {
        [Serializable]
        public sealed class UnitIcon
        {
            public string unitId;
            public Sprite sprite;
        }

        public Sprite energyA;
        public Sprite energyB;
        public Sprite hammer;
        public Sprite xp;
        public Sprite blank;
        public Sprite padlock;
        public Sprite crown;
        public Sprite wall;
        public Sprite bomb;
        public List<UnitIcon> units = new List<UnitIcon>();

        public Sprite Unit(string unitId)
        {
            foreach (var u in units) if (u.unitId == unitId) return u.sprite;
            return null;
        }

        /// <summary>True when every required sprite is assigned.</summary>
        public bool IsComplete =>
            energyA != null && energyB != null && hammer != null && xp != null && blank != null && padlock != null
            && crown != null && wall != null && bomb != null && Unit("striker") != null && Unit("caster") != null;
    }
}
